### ISSUE TITLE
Users are unable to post issues

### ISSUE THREAD

**Issue by sverress** [hovedstyret/indok-web#118]
### How to reproduce this bug
Go to the bottom of the page and click on "GitHub" in the sentence "Lag en issue på GitHub" in incognito mode. This will direct you to a 404 on GitHub. 

### Possible fix
Since our repo is private there is no straightforward way to allow non-members of the repo to create issues. However, there are the two solutions presented in [this StackOverflow issue](https://stackoverflow.com/questions/11503246/how-to-have-a-private-repository-with-public-issue-tracker-on-github):
1. Using something called [Bitbucket](https://bitbucket.org/)
2. Creating a separate public repo only for issues from the public

**Comment by larwaa** [comment]
Resolved as we are now open source.
